### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by Saurav-cmd** [Saurav-cmd/Capstone-Project#11]
Notification: **Users can get notification about the products.**

**Comment by mtrigo-fol** [comment]
Notification of **what?**

**Comment by Saurav-cmd** [comment]
Notification of the latest offers in booze

**Comment by mtrigo-fol** [comment]
> Notification of the latest offers in booze

Then I would update the feature description to say that.

I would also check for any feedback under the Project Schedule about issue's descriptions

**Comment by mtrigo-fol** [comment]
Make the notification about reminding the user to buy the drinks for a Wishlist/Shopping List

"Users can add a date to a wishlist to be notified to buy the drinks for the occasion"
