### ISSUE TITLE
WishList Management

### ISSUE THREAD

**Issue by Saurav-cmd** [Saurav-cmd/Capstone-Project#5]
Wishlist Management: Users can **Add, view and delete ** there Wish List

**Comment by Ttashi911** [comment]
Due to misunderstanding I had been working and making commit using normal way until recently I saw your video and made a commit using the backlog way.

**Comment by mtrigo-fol** [comment]
Change this feature from a "Shopping Cart" to a "Wishlist" or "Shopping List".

Example:

Someone's birthday is July 1st. You're making a wishlist called "Friend's Birthday" with a date and several items to buy.

This **INCLUDES** deleting and updating these wishlists
