### ISSUE TITLE
Share WishList

### ISSUE THREAD

**Issue by Saurav-cmd** [Saurav-cmd/Capstone-Project#7]
Share WishList: Users can **Share there wishlist**

**Comment by gudwin1314** [comment]
I have committed all the changes initially as a normal commit while working on the issues. Later came to know that I have specifically commit  using the Backlog, that's why I have near different changes as a commit.

**Comment by mtrigo-fol** [comment]
This is not a complete feature on its own, at best it would be included inside of the "Cart" of "Wishlist" feature

Update this to be a "Share a Wishlist"
